[build]
builder = "NIXPACKS"

[build.buildCommand]
value = "python -m pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"

[build.watchPatterns]
include = ["**/*.py", "**/*.html", "**/*.css", "**/*.js", "requirements.txt"]

[deploy]
startCommand = "python manage.py runserver 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
RAILWAY_ENVIRONMENT = "production"
DJANGO_DEBUG = "False"
DJANGO_SECRET_KEY = { generate = true }
