# Generated by Django 4.2.7 on 2025-09-09 17:58

from django.db import migrations, models
import remover.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to=remover.models.upload_to_uploads)),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to=remover.models.upload_to_processed)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('original_width', models.PositiveIntegerField(blank=True, null=True)),
                ('original_height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_size', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Image Processing',
                'verbose_name_plural': 'Image Processings',
                'ordering': ['-created_at'],
            },
        ),
    ]
